run:
	g++ ./src/PoligonoIrreg.cpp -c -o ./src/PoligonoIrreg.o
	g++ ./src/Coordenada.cpp -c -o ./src/Coordenada.o
	g++ ./src/main.cpp ./src/PoligonoIrreg.o ./src/Coordenada.o -o main
clean:
	
	-rm ./src/main