run:
	g++ ./src/Rectangulo.cpp -c -o ./src/Rectangulo.o
	g++ ./src/Coordenada.cpp -c -o ./src/Coordenada.o
	g++ ./src/main.cpp ./src/Rectangulo.o ./src/Coordenada.o -o main
clean:
	-rm ./lib/Fecha/Fecha.o
	-rm ./src/main